version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped

    volumes:
        - ./hosts:/etc/nginx/conf.d

    ports:
      - "80:80"
      - "443:443"


networks:
  petobots-network:
    external:
      name: petobots-network
  carbar-network:
    external:
      name
